# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hook
default_stages:
  - commit
  - push
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        language_version: python3.10
        exclude: ^migrations/
        args: [--no-strict-optional, --ignore-missing-imports, --install-types, --non-interactive]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^migrations/
        language_version: python3.10
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
    -   id: check-yaml
    -   id: check-json
    -   id: detect-private-key
    -   id: check-case-conflict
        exclude: ^migrations/
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--ignore=F401,E501']
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.1.0
    hooks:
    -   id: rm-unneeded-f-str
